markdown: kramdown
highlighter: rouge
permalink: pretty
excerpt_separator: "<!-- more -->"

github: panxw
author: "panxw"
email: winfirm#163.com
name: "Panxw's Blog"
baseurl: /
url: http://www.panxw.com
domain: www.panxw.com

all_categories: [
  ["android", "Python 学习","/posts/android.html"], 
  ["react", "ReactNavtive","/posts/react.html"], 
  ["web", "工具使用","/posts/web.html"], 
  ["read", "读书笔记","/posts/read.html"], 
  ["about", "关于","/about.html"]
]

paginate: 8 
paginate_path: "/page:num/"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
gems: [jekyll-paginate]
# gems: [jekyll-paginate]

# -----------------------------------------------------------------------------
#  Collections
# -----------------------------------------------------------------------------
# collections:
#   featured_categories:
#     permalink:       /category/:name/
#     output:          true
#   featured_tags:
#     permalink:       /tag/:name/
#     output:          true
#   projects:
#     permalink:       /projects/:path/
#     output:          true



copyright: []
#timezone: Asia/Shanghai
