markdown: kramdown
# kramdown : markdown의 개조판.
# markdown에서 불편한 사항을 개선한 형태.

highlighter: rouge
# text highlighter로 rouge이용
# 2016.02월 이후로 syntax highlighter는 rouge만 지원.
# Pygments 사용불가.

permalink: pretty

github: kodaewon
author: "kodaewon"
email: rheodnjs23@naver.com
name: "iOS Developer"
baseurl: /
url: http://kodaewon.github.io
domain: kodaewon.github.io

all_categories: [
  ["ios", "iOS","/posts/ios/index.html"], 
  ["react", "ReactNavtive","/posts/react/index.html"], 
  ["algorithm", "Algorithm", "/posts/algorithm/index.html"],
  ["read", "기타","/posts/read/index.html"], 
  # ["bio", "일대기","/posts/bio/index.html"], 
  # ["about", "About","/about/index.html"]
]

paginate: 8 
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - rouge

# -----------------------------------------------------------------------------
#  Collections
# -----------------------------------------------------------------------------
# collections:
#   featured_categories:
#     permalink:       /category/:name/
#     output:          true
#   featured_tags:
#     permalink:       /tag/:name/
#     output:          true
#   projects:
#     permalink:       /projects/:path/
#     output:          true

copyright: []
#timezone: Asia/Shanghai
