markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: cxdhacks
author: "陈锡冬"
email: chinachenxidong@gmail.com
name: "陈锡冬的个人博客"
url: https://kodaewon.github.io

all_categories: [
["android", "Python 学习","/posts/android.html"], 
["web", "工具使用","/posts/web.html"], 
["read", "读书笔记","/posts/read.html"], 
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
