markdown: kramdown
highlighter: rouge
permalink: pretty
excerpt_separator: "<!-- more -->"

github: kodaewon
author: "kodaewon"
email: rheodnjs23@naver.com
name: "iOS Developer"
baseurl: /
url: http://kodaewon.github.io
domain: kodaewon.github.io

all_categories: [
  ["ios", "iOS","/posts/ios/index.html"], 
  ["react", "ReactNavtive","/posts/react/index.html"], 
  ["read", "기타","/posts/read/index.html"], 
  ["bio", "일대기","/posts/bio/index.html"], 
  ["about", "About","/about/index.html"]
]

paginate: 8 
paginate_path: "/page:num/"

gems: [jekyll-paginate]

# -----------------------------------------------------------------------------
#  Collections
# -----------------------------------------------------------------------------
# collections:
#   featured_categories:
#     permalink:       /category/:name/
#     output:          true
#   featured_tags:
#     permalink:       /tag/:name/
#     output:          true
#   projects:
#     permalink:       /projects/:path/
#     output:          true



copyright: []
#timezone: Asia/Shanghai
